stages:

 ## The first stage
 Run Quality Checks:  
   actions:
     - type: liquibase
       command: checks run
       cmdArgs: {checks-scope: changelog}

 ## The second stage of actions.
 Update Database:
   actions:
     - type: liquibase
       command: update-sql

     - type: liquibase
       command: update


## If you do not want any actions to ALWAYS RUN, 
##   simply delete the endStage from your flow file.

endStage:
 actions:
   - type: liquibase
     command: history